/* ============================================================
   ULT11-HITFX  ·  Ultimate Eleven   (author 2026-10-01)
   Plays the slash / hit VFX sheets (assets/vfx/slash_<palette>.png,
   25 frames of 256 px on a 5x5 grid, generated by
   art/vfx_slash/slash_generator.js) as a short screen-space flash at a
   point - drawn additively ('screen' blend) over the match.
   First use: the keeper SAVES a super shot (ult11-pitch3d.js, the
   cinematic's arrival): blue (home) = the player's keeper, red (away) = the CPU's.
   API: U11HitFX.play(clientX, clientY, {pal:'home'|'away', size, fps, track})
   track: optional ()=>{x,y} in client px, read every frame so the flash stays
   ON the point (the keeper's glove) while the camera and the dive keep moving
   (author 2026-10-02: "not exactly on the fist of the gk, a little far off").
   ============================================================ */
(function(){
'use strict';
const HF={ fps:18, frames:25 };
window.U11HitFX=HF;
const sheets={};
function sheet(pal){
  if(!sheets[pal]){ const im=new Image(); im.src='assets/vfx/slash_'+pal+'.png'; sheets[pal]=im; }
  return sheets[pal];
}
['home','away'].forEach(sheet);                // load up front: the first save must not wait for it
HF.play=function(x,y,o){
  o=o||{}; const im=sheet(o.pal||'home'); if(!im.complete||!im.naturalWidth) return false;
  const size=Math.round(o.size||Math.min(innerHeight*0.62,innerWidth*0.42)), fps=o.fps||HF.fps;
  const c=document.createElement('canvas'), dpr=Math.min(2,devicePixelRatio||1);
  c.width=c.height=Math.round(size*dpr);
  c.style.cssText='position:fixed;pointer-events:none;z-index:2500;mix-blend-mode:screen;   /* under the SAVED! banner (2600) */'+
    'width:'+size+'px;height:'+size+'px;left:'+(x-size/2)+'px;top:'+(y-size/2)+'px;'+
    (o.rot?'transform:rotate('+o.rot+'deg);':'')+(o.flip?'transform:scaleX(-1)'+(o.rot?' rotate('+o.rot+'deg)':'')+';':'');
  document.body.appendChild(c);
  const g=c.getContext('2d'), t0=performance.now();
  (function step(){
    const f=Math.floor((performance.now()-t0)/1000*fps);
    if(f>=HF.frames){ c.remove(); return; }
    if(o.track){ try{ const p=o.track(); if(p&&isFinite(p.x)&&isFinite(p.y)){ c.style.left=(p.x-size/2)+'px'; c.style.top=(p.y-size/2)+'px'; } }catch(e){} }
    g.clearRect(0,0,c.width,c.height);
    g.drawImage(im,(f%5)*256,Math.floor(f/5)*256,256,256,0,0,c.width,c.height);
    requestAnimationFrame(step);
  })();
  return true;
};
})();
